#### Numpy

* 方便地做一些矩阵和大数据的运算
* quick
    * 底层通过C++实现
    * 矩阵和向量的一些操作是可以通过多线程并发来加速计算的，而Python本身的特性导致了Python不能执行这样的操作。那么通过Python调用C++实现的计算库也就是唯一的选择了
* ndarray:存储高维数组的对象
* mat:存储矩阵
* 支持的类型
    - int:int8，int32，int64和int128，其中每一种又分为带符号的和不带符号,uint8
    - float:float16，float32，float64和flaot128
    - 复数类型complex complex64，complex128和complex256
    - string
    - object
    - unicode

In [2]:
import numpy as np

##### 创建

In [3]:
nums = [1,4,6,8]
np.array(nums)

array([1, 4, 6, 8])

In [7]:
array = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float64)
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
ex1 = np.arange(10)
ex1.astype(np.float64)
ex1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(10, dtype=np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [26]:
# 生成一个同样大小的全为0的矩阵
np.zeros_like(ex1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.zeros(ex1.shape)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# 单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.full((3,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [1]:
arr = np.zeros((10, 10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.random.randn(3,4,5)

array([[[-0.10439178, -0.34210485,  0.28630928, -0.41259482,
         -1.6142529 ],
        [-0.36240721, -1.07240346, -1.14373912,  0.02145129,
         -0.42747907],
        [-0.65090762, -0.6266369 ,  2.91882176,  1.01665294,
          1.66269368],
        [ 0.12894962, -0.62013061,  0.90006931,  0.81765151,
         -0.99074674]],

       [[-0.26696056,  0.01526727,  0.28433782, -0.3038405 ,
          0.74619585],
        [-0.59133881, -0.14281332, -1.96612164,  0.44938685,
          1.55540036],
        [ 1.11555362,  1.40065089, -0.8658811 , -1.21690126,
          2.17504054],
        [ 0.46376134,  0.07078334,  2.18198414,  0.44337681,
         -1.44498089]],

       [[ 0.59659333, -0.01232263, -0.00423229,  0.92620785,
          1.08111595],
        [ 1.72501097,  2.15004124,  0.43214144, -0.08813626,
          0.08732635],
        [ 0.69315737, -0.01254323,  0.46458182,  0.74055182,
          0.60968166],
        [-0.70719617,  0.96454134, -0.40596633,  0.22371514,
          0

array([[[19, 14, 16,  5,  3],
        [ 6,  0, 15, 16, 15],
        [11, 13, 10,  6, 13],
        [ 9,  7,  8, 18, 14]],

       [[ 7, 12,  1,  1,  5],
        [11,  7, 18, 13,  4],
        [14,  7,  2,  9,  9],
        [14,  8, 10,  0,  5]],

       [[18,  2,  8,  1, 17],
        [ 9, 16,  2,  6,  1],
        [ 4, 18, 10,  3, 14],
        [ 5,  8, 18,  9,  4]]])

In [2]:
a = np.empty((3,4), dtype=np.int)
print(a)

[[94538226783792              0              0              0]
 [             0              0              0              0]
 [             0              0              0              0]]


In [5]:
# 有序
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(np.linspace(0,11,12, dtype=np.int).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


##### property

In [5]:
# 维度
arr.ndim

2

In [5]:
# 各个维度值
arr.shape

NameError: name 'arr' is not defined

In [6]:
arr.size

NameError: name 'arr' is not defined

In [7]:
# 元素类型
arr.dtype

dtype('float64')

In [11]:
# 转化成Python原生的list进行返回
arr.tolist()

NameError: name 'arr' is not defined

##### 运算

In [15]:
a = np.array([10,20,30,40])
b= np.arange(4)
a-b

array([10, 19, 28, 37])

In [24]:
a+b

array([10, 21, 32, 43])

In [25]:
a*b

array([  0,  20,  60, 120])

In [26]:
# 矩阵乘法
np.dot(a,b)

200

In [19]:
b**2

array([0, 1, 4, 9])

In [43]:
10*np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [45]:
randint = np.random.randint(0,20,size=(3,4,5))
randint

array([[[ 2, 12, 13,  5, 19],
        [ 6, 17,  3, 16,  4],
        [ 0, 16,  7, 19, 17],
        [ 1, 18, 13, 14, 10]],

       [[ 3,  7, 19, 15,  6],
        [ 0,  5, 10, 15, 17],
        [13, 13,  3, 14,  2],
        [ 7,  8, 19,  4,  2]],

       [[16,  5,  2, 16,  3],
        [ 5, 11,  0,  0, 18],
        [ 3,  9, 17,  7,  8],
        [ 4,  8, 17, 11,  8]]])

In [46]:
randint.sum()

562

In [48]:
# 三维投影
# 压缩x轴
randint.sum(axis=0)

array([[21, 24, 34, 36, 28],
       [11, 33, 13, 31, 39],
       [16, 38, 27, 40, 27],
       [12, 34, 49, 29, 20]])

In [50]:
# 压缩z轴
randint.sum(axis =1)

array([[ 9, 63, 36, 54, 50],
       [23, 33, 51, 48, 27],
       [28, 33, 36, 34, 37]])

In [52]:
# 最大值索引
np.argmin(randint)

10

In [54]:
# 最小值索引
np.argmax(randint)

4

In [57]:
randint.mean()

9.366666666666667

In [59]:
np.average(randint)

9.366666666666667

In [61]:
np.median(randint)

8.0

In [63]:
np.cumsum(randint)

array([  2,  14,  27,  32,  51,  57,  74,  77,  93,  97,  97, 113, 120,
       139, 156, 157, 175, 188, 202, 212, 215, 222, 241, 256, 262, 262,
       267, 277, 292, 309, 322, 335, 338, 352, 354, 361, 369, 388, 392,
       394, 410, 415, 417, 433, 436, 441, 452, 452, 452, 470, 473, 482,
       499, 506, 514, 518, 526, 543, 554, 562])

In [65]:
# 后一项 减前一项
np.diff(randint)

array([[[ 10,   1,  -8,  14],
        [ 11, -14,  13, -12],
        [ 16,  -9,  12,  -2],
        [ 17,  -5,   1,  -4]],

       [[  4,  12,  -4,  -9],
        [  5,   5,   5,   2],
        [  0, -10,  11, -12],
        [  1,  11, -15,  -2]],

       [[-11,  -3,  14, -13],
        [  6, -11,   0,  18],
        [  6,   8, -10,   1],
        [  4,   9,  -6,  -3]]])

In [69]:
A = np.random.randint(0,10,size=(3,4))
A

array([[9, 7, 8, 0],
       [4, 1, 7, 3],
       [7, 9, 7, 6]])

In [79]:
np.nonzero(A)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [80]:
# 每行排序
A.sort()
A

array([[0, 7, 8, 9],
       [1, 3, 4, 7],
       [6, 7, 7, 9]])

In [82]:
A.transpose()

array([[0, 1, 6],
       [7, 3, 7],
       [8, 4, 7],
       [9, 7, 9]])

In [84]:
A.T

array([[0, 1, 6],
       [7, 3, 7],
       [8, 4, 7],
       [9, 7, 9]])

In [86]:
# 截取
A.clip(3,8)

array([[3, 7, 8, 8],
       [3, 3, 4, 7],
       [6, 7, 7, 8]])

In [88]:
# 切片
A[1:,:-1]

array([[1, 3, 4],
       [6, 7, 7]])

In [90]:
for row in A:
    print(row)

[0 7 8 9]
[1 3 4 7]
[6 7 7 9]


In [93]:
for col in A.T:
    print(col)

[0 1 6]
[7 3 7]
[8 4 7]
[9 7 9]


In [96]:
A.flatten()

array([0, 7, 8, 9, 1, 3, 4, 7, 6, 7, 7, 9])

In [102]:
# 合并
B = np.array([1,1,1])
C = np.array([2,2,2])
np.vstack((B,C,B))

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [108]:
np.hstack((B.T,C.T,B.T))

array([1, 1, 1, 2, 2, 2, 1, 1, 1])

In [112]:
B[:,np.newaxis, np.newaxis]

array([[[1]],

       [[1]],

       [[1]]])

In [114]:
A 

array([[0, 7, 8, 9],
       [1, 3, 4, 7],
       [6, 7, 7, 9]])

In [119]:
np.split(A,4, axis=1)

[array([[0],
        [1],
        [6]]),
 array([[7],
        [3],
        [7]]),
 array([[8],
        [4],
        [7]]),
 array([[9],
        [7],
        [9]])]

In [123]:
D = A.copy()
D[2][3] = 56
D

array([[ 0,  7,  8,  9],
       [ 1,  3,  4,  7],
       [ 6,  7,  7, 56]])

In [124]:
A

array([[0, 7, 8, 9],
       [1, 3, 4, 7],
       [6, 7, 7, 9]])