In [3]:
from __future__ import print_function
import torch

x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1704e-41],
        [0.0000e+00, 2.2369e+08, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [       nan,        nan, 1.4537e+05]])


In [22]:
x = torch.rand(5,3)
print(x)

tensor([[0.6558, 0.4197, 0.1499],
        [0.2792, 0.9780, 0.3950],
        [0.9231, 0.2002, 0.2035],
        [0.0479, 0.6651, 0.3891],
        [0.1921, 0.6274, 0.0250]])


In [23]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [24]:
x= torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
y = torch.rand(5, 3)
print(x + y)

tensor([[4.6311e-01, 6.2607e-01, 1.7989e-01],
        [9.7894e-01, 3.3439e-01, 9.3502e-01],
        [7.8708e-01, 2.2369e+08, 1.9149e-01],
        [6.9530e-01, 1.9271e-02, 9.5582e-01],
        [       nan,        nan, 1.4537e+05]])


In [6]:
print(torch.add(x, y))

tensor([[4.6311e-01, 6.2607e-01, 1.7989e-01],
        [9.7894e-01, 3.3439e-01, 9.3502e-01],
        [7.8708e-01, 2.2369e+08, 1.9149e-01],
        [6.9530e-01, 1.9271e-02, 9.5582e-01],
        [       nan,        nan, 1.4537e+05]])


In [7]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[4.6311e-01, 6.2607e-01, 1.7989e-01],
        [9.7894e-01, 3.3439e-01, 9.3502e-01],
        [7.8708e-01, 2.2369e+08, 1.9149e-01],
        [6.9530e-01, 1.9271e-02, 9.5582e-01],
        [       nan,        nan, 1.4537e+05]])


In [8]:
y.add_(x)

tensor([[4.6311e-01, 6.2607e-01, 1.7989e-01],
        [9.7894e-01, 3.3439e-01, 9.3502e-01],
        [7.8708e-01, 2.2369e+08, 1.9149e-01],
        [6.9530e-01, 1.9271e-02, 9.5582e-01],
        [       nan,        nan, 1.4537e+05]])

In [9]:
print(x[:1])

tensor([[0., 0., 0.]])


In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
a = torch.ones(5)
print(a)